remove error-causing lines in head.html (google analytics)
https://discourse.gohugo.io/t/error-error-building-site/49340

error: execute of template failed: template: index.html:3:8: executing "index.html" at <partial "head.html" .>: error calling partial: execute of template failed: html/template:partials/head.html:39:20: no such template "_internal/google_analytics_async.html"